# from https://github.com/nelmio/NelmioApiDocBundle/blob/1302bc7568fc1ead9304b8c11d3d2fe5c7ba76c9/.github/workflows/continuous-integration.yml
name: "CI"

on:
  pull_request:
    branches:
      - "*.x"
      - main
  push:
    branches:
      - "*.x"
      - main

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
        symfony-require:
          - '5.4.*'
          - '6.*'
          - '7.*'
        composer-flags:
          - ''
          - '--prefer-lowest'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP without coverage"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer
          coverage: "none"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install dependencies with composer"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --no-progress ${{ matrix.composer-flags }}
      - name: "Run PHPUnit"
        run: ./vendor/bin/phpunit
